#############################################################################
# Makefile for building: HeadCountsReplay
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Jul 26 13:20:53 2010
# Project:  HeadCounts.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile HeadCounts.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       =
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES) -fopenmp
CXXFLAGS      = -O2 -O2 -Wall -W -D_REENTRANT $(DEFINES) -fopenmp
INCPATH       = -I/usr/include/opencv -I.
LINK          = g++
LFLAGS        = -Wl,-O1
#LIBS          = $(SUBLIBS)  -L/usr/lib -lopencv_legacy -lopencv_core -lopencv_highgui -lopencv_objdetect -lpthread
LIBS          = $(SUBLIBS)  -L/usr/lib -lopencv_core -lopencv_video -lopencv_highgui -lpthread
AR            = ar cqs
RANLIB        =
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: cvplayer headcounter



clean:
	-$(DEL_FILE) *.o
	-$(DEL_FILE) *~ core *.core


cvplayer: cvPlayer/cvPlayer.cpp
	$(CXX) $(CXXFLAGS) $(LFLAGS) $(LIBS)  $(INCPATH) -o "$@" "$<"

headcounter: headCounter.o haar_modified.o
	$(CXX) $(CXXFLAGS) $(LFLAGS) $(LIBS)  $(INCPATH) -o "$@" $^
